[feat/EATBOOK-97] 소설 리스트 조회 요청 API 구현
ktb-eatbook/eatbook-backoffice-backend pull request #7
Opened 2024-11-07 22:27 UTC by pletain

## 설명
- 이 PR을 소설 리스트 조회 기능을 도입합니다. 

## 포함된 변경 사항
- 기존 Controller에서 JSON 타입을 받을 수 있도록 @RequestBody 추가
- 소설 리스트 조회 관련 Controller, Service, Repository 구현
- 소설 리스트 조회 관련 예외, 에러코드, 성공코드 생성
- 소설 리스트 조회 관련 관련 테스트 코드 추가
  - 여러 페이지가 있을 때 적절한 페이지와 함께 요청하면 소설 리스트를 성공적으로 반환
  - 전체 페이지를 넘기는 페이지에 대한 요청은 PageOutOfBoundException 발생

## 추가 참고 사항
- 해당 기능 구현 과정에서 N+1 이슈가 있었는데, MVP 이후에 추가적으로 같이 실험 및 성능 측정해보면 좋을거 같습니다!
- 관련 내용은 [팀 노션 페이지](https://cjm-0611.notion.site/N-1-b7794096f31945e7a8805730c1b7535c?pvs=4)에 정리해두었으니, 참고해주세요 :)

## 리뷰 요청 사항
전체적인 코드의 가독성과 구조, 변경된 코드 내역에 대해 확인 부탁드립니다!

2024-11-08 01:17 UTC, cjm0611 requested changes

2024-11-08 01:17 UTC, cjm0611 commented on src/main/java/com/eatbook/backoffice/domain/novel/controller/NovelController.java
> +    @GetMapping("/list")
RESTful API에서는 명사형 복수를 이용해 리소스가 컬렉션임을 의미하는 것으로 알고 있습니다.
`/api/admin/novel/list` 보다는 `/api/admin/novels`로 작성하면 어떨까요?

2024-11-08 01:17 UTC, cjm0611 commented on src/main/java/com/eatbook/backoffice/domain/novel/dto/NovelListResponse.java
> +// NovelListResponse.java
불필요한 주석 지워주세요!

2024-11-08 01:17 UTC, cjm0611 commented on src/main/java/com/eatbook/backoffice/domain/novel/exception/PageOutOfBoundException.java
> +public class PageOutOfBoundException  extends BusinessException {
현재 공백이 2개 들어가 있는 것으로 보입니다. 개인적으로는 이러한 공백 오류는 정형화된 코드 스타일이 아니라 코드의 가독성을 낮춘다고 생각합니다. `Google Java Style Guide`와 같은 스타일 가이드를  IntelliJ에서 제공하는 Code Style 설정에 적용해서 자동 코드 포맷팅을 적용하면 어떨까요?

2024-11-08 01:17 UTC, cjm0611 commented on src/test/java/com/eatbook/backoffice/domain/novel/service/NovelServiceTest.java
> +        assertEquals((novels.size()+size-1)/size, result.totalPages());
`(novels.size() + size - 1) / size` 계산 식을 별도의 변수로 분리하면 어떨까요?
e.g. `int expectedTotalPages = int totalPages = (totalElements + size - 1) / size;`
또한 예상되는 결과에 대한 변수이므로 given에 위치하면 좋을 것 같습니다.

2024-11-08 01:24 UTC, cjm0611 commented
작성해주신 문서 잘 읽었습니다! 개인적으로 `N+1` 문제를 해결하면서 카운트 쿼리도 함께 해결하여 쿼리 성능을 높이신 점이 인상깊네요 👍
NovelAuthor과 NovelCategory의 개수는 일정 범위가 정해져 있으므로 MVP 개발 이후에 Batch Fetching이랑 성능 비교해보면 좋을 것 같아요. 현재와 같은 구조로 Fetch Join을 사용하면 `Novel 수 × NovelAuthor 수 × NovelCategory 수`만큼 메모리에 올라가게 되는데, Batch Fetching을 사용하면 `Novel 수 + NovelAuthor 수 + NovelCategory 수`만큼 메모리에 올라가게 되어 효율적일 것 같습니다. 쿼리의 개수가 1개에서 3개로 늘어나는 단점도 있으면서, 각 쿼리문의 join이 간단해지는 장점이 있을 것 같아 수치적으로 비교해야할 것 같습니다. 데이터셋이 크지 않은 테이블이라 생각되어 Fetch Join이 성능적으로 더 좋지 않을까 하는 추측이 들긴 합니다. 문서 흥미롭게 읽었습니다 감사합니다!

2024-11-11 06:34 UTC, pletain commented on src/main/java/com/eatbook/backoffice/domain/novel/controller/NovelController.java
> +    @GetMapping("/list")
지적 감사합니다! 수정하도록 하겠습니다!

2024-11-11 06:56 UTC, pletain commented on src/test/java/com/eatbook/backoffice/domain/novel/service/NovelServiceTest.java
> +        assertEquals((novels.size()+size-1)/size, result.totalPages());
좋은 생각인거 같습니다. 별도로 분리하는 편이 가독성 측면에서 더 명확할거 같습니다!

2024-11-15 06:45 UTC, cjm0611 approved these changes

2024-11-15 06:45 UTC, merged