[feat/EATBOOK-99] 소설 상세정보 조회 요청 API 구현
ktb-eatbook/eatbook-backoffice-backend pull request #8
Opened 2024-11-18 02:37 UTC by pletain

## 설명
- 이 PR을 소설 상세정보 조회 기능을 도입합니다. 
- CORS 설정을 도입합니다.

## 포함된 변경 사항
- 소설 상세정보 조회 관련 Controller, Service, Repository 구현
- 소설 리스트 조회 관련 성공코드 추가
- QueryDSL 설정 추가
- 관련 테스트 코드 추가
  - 유효한 소설 Id가 제공될 시 소설 상세 정보 반환
  - 유효하지 않은 소설 Id가 제공될 시 NovelNotFoundException 예외 발생

## 리뷰 요청 사항
전체적인 코드의 가독성과 구조, 변경된 코드 내역에 대해 확인 부탁드립니다!

2024-11-20 01:17 UTC, cjm0611 requested changes

2024-11-20 01:17 UTC, cjm0611 commented on src/main/generated/com/eatbook/backoffice/entity/QAuthor.java
빌드 과정에서 자동으로 생성되는`src/main/generated`의 파일들은 gitignore에 포함해주시면 감사하겠습니다!

2024-11-20 01:17 UTC, cjm0611 commented on src/main/java/com/eatbook/backoffice/domain/novel/service/NovelService.java
> +        return novelDetail;
`return novelRepository.findNovelDetailById(novelId);`처럼 간결하게 작성해주세요!

2024-11-20 01:17 UTC, cjm0611 commented on src/test/java/com/eatbook/backoffice/domain/novel/service/NovelServiceTest.java
> +        assertEquals(expectedResponse.likes(), result.likes());
DTO 객체 간 모든 필드를 비교하면서 동등성을 확인하는 것 같은데, `usingRecursiveComparison` 메서드를 사용해보면 어떨까요?
내부에서 재귀적으로 두 객체 간의 모든 값이 같은지 확인해줍니다. 이런 코드로 작성하면 두 객체의 모든 값이 같아야한다는 의미가 정확히 전달되고, 실수로 일부 필드를 빠뜨리는 실수도 줄일 수 있을 것 같아요.

2024-11-21 08:09 UTC, pletain commented on src/test/java/com/eatbook/backoffice/domain/novel/service/NovelServiceTest.java
> +        assertEquals(expectedResponse.likes(), result.likes());
오 `usingRecursiveComparison`를 사용하면 훨씬 간단하고 가독성도 좋아지고 유연하게 사용할 수 있군요! 감사합니다!

2024-11-21 08:13 UTC, cjm0611 approved these changes

2024-11-21 08:27 UTC, merged